from math import floor
from pathlib import Path

MAX_LONGITUDE = 180
MIN_LONGITUDE = -MAX_LONGITUDE
MAX_LATITUDE = 85.0511287798
MIN_LATITUDE = -MAX_LATITUDE

MAX_CENTER_LONGITUDE = floor(MAX_LONGITUDE -2)
MIN_CENTER_LONGITUDE = -MAX_CENTER_LONGITUDE
MAX_CENTER_LATITUDE = floor(MAX_LATITUDE -2)
MIN_CENTER_LATITUDE = -MAX_CENTER_LATITUDE

DEFAULT_LAT = 49.836
DEFAULT_LON = 24.006

DEFAULT_MIN_ZOOM = 1
DEFAULT_MAX_ZOOM = 17
DEFAULT_MAPS_DIRECTORY = 'map'
DEFAULT_MAP_BASENAME = 'map'
PNG_PATH = Path(__file__).resolve().with_name("png")

DOWNLOAD_PANEL_BACKGROUND = (0.95, 0.95, 0.95, 1)
HEADER_BACKGROUND = (0.5, 0.5, 0.5, 1)
HEADER_TEXT_COLOR = (1, 1, 1, 1)
TEXT_COLOR = (0, 0, 0, 1)
FONT_SIZE_MEDIUM = '16sp'
FONT_SIZE_SMALL = '14sp'

DROPDOWN_DOWN_PNG = str(PNG_PATH / 'dropdown_down.png')
DROPDOWN_UP_PNG = str(PNG_PATH / 'dropdown_up.png')
INPUT_INCREASE_PNG = str(PNG_PATH / 'input_increase.png')
INPUT_DECREASE_PNG = str(PNG_PATH / 'input_decrease.png')
FOLDER_PNG = str(PNG_PATH / 'folder.png')
ZOOM_IN_PNG = str(PNG_PATH / 'zoom_in.png')
ZOOM_OUT_PNG = str(PNG_PATH / 'zoom_out.png')

CUSTOM_PROVIDER_KEY = 'Your custom'
